import type { Clip, ClipEditState, VideoType } from './types'
import { initialClipEditForVideoType } from './videoType'

/**
 * Which clips get their reframe analysis during the pipeline, and how a
 * finished analysis is grafted onto a clip that may have been edited since.
 *
 * Reframe analysis (face detection + LR-ASD at 25 fps) is a substantial
 * per-clip stage: it can take tens of seconds of CPU per clip, against a few seconds for
 * everything else. Running it for every candidate made an hour of source
 * video take most of an hour to come back, most of it spent on clips the
 * user would never open. So the pipeline analyses only the top tier and the
 * rest are analysed on demand — when the clip is opened in the editor or
 * exported (see main/pipeline/reframe.ts).
 */

/** Clips always analysed up front, however they score. */
export const EAGER_REFRAME_MIN = 8
/** Beyond the minimum, clips scoring at least this are also analysed up front… */
export const EAGER_REFRAME_SCORE = 80
/** …up to this many in total. */
export const EAGER_REFRAME_MAX = 12

/**
 * Ids of the clips the pipeline should analyse eagerly. Input is the ranked
 * list (highest score first); ties are resolved by rank. Pure and exported
 * for tests.
 */
export function selectEagerReframeIds(ranked: Clip[]): Set<string> {
  const eager = new Set<string>()
  for (const clip of ranked) {
    if (eager.size >= EAGER_REFRAME_MAX) break
    if (eager.size < EAGER_REFRAME_MIN || clip.viralityScore >= EAGER_REFRAME_SCORE) {
      eager.add(clip.id)
    }
  }
  return eager
}

/** Whether a clip still needs its reframe analysis before it is fully framed. */
export function needsReframe(clip: Clip): boolean {
  const coverage = clip.reframeAnalysis ?? { start: clip.suggestedStart, end: clip.suggestedEnd }
  return clip.reframeStatus === 'pending' ||
    // Revisit old context-preserving letterboxes once when opened. Leave
    // accepted composites and manual source corrections alone.
    needsLayoutUpgrade(clip) ||
    clip.edit.start < coverage.start - 0.001 || clip.edit.end > coverage.end + 0.001
}

/** A clip can be edited before framing is ready; this describes only framing work. */
export function framingReadiness(
  clip: Clip,
  processing: boolean,
  error?: string
): 'ready' | 'preparing' | 'pending' | 'failed' {
  if (processing) return 'preparing'
  if (!needsReframe(clip)) return 'ready'
  return error ? 'failed' : 'pending'
}

/** The letterbox defaults generated by the old context guard, not a custom crop. */
function needsLayoutUpgrade(clip: Clip): boolean {
  // Version 1 proves a previous completed analysis. New pending clips have no
  // such evidence, and explicit choices also protect legacy clips mid-upgrade.
  return Boolean(clip.reframeAnalysis?.version === 1 &&
    !clip.edit.layoutChosen && clip.visualLayout?.preserveContext && !clip.visualLayout.revision &&
    !clip.visualLayout.shots?.some(s => s.composition || s.region || s.mode === 'crop') &&
    clip.edit.reframeMode === 'fit-letterbox' && clip.edit.framing === 'manual' &&
    clip.edit.focusX === .5 && !clip.edit.autoZoom &&
    (!clip.edit.compositionPreference || clip.edit.compositionPreference === 'auto'))
}

/** Record only the interval the analysis actually saw, including no-face results. */
export function markReframeComplete(clip: Clip): void {
  clip.reframeStatus = 'done'
  clip.reframeAnalysis = { start: clip.edit.start, end: clip.edit.end, version: 2 }
}

/** Main owns analysis metadata, but an ordinary save must preserve chosen layout edits. */
export function mergeClipSave(incoming: Clip, saved: Clip, videoType: VideoType): Clip {
  const retried = (saved.reframeAnalysis?.revision ?? 0) > (incoming.reframeAnalysis?.revision ?? 0)
  const merged = mergeReframeResult(incoming, saved, videoType, retried)
  const analysisLanded = (retried || incoming.reframeStatus === 'pending' || needsLayoutUpgrade(incoming)) && !needsReframe(saved)
  return analysisLanded ? merged : { ...merged, edit: incoming.edit }
}

/** The layout fields the reframe analysis sets defaults for. */
const LAYOUT_FIELDS = ['reframeMode', 'framing', 'focusX', 'autoZoom', 'compositionPreference'] as const

/** Remember intent rather than inferring it from values after an async result. */
export function userClipEdit(current: ClipEditState, patch: Partial<ClipEditState>): ClipEditState {
  return { ...current, ...patch,
    layoutChosen: current.layoutChosen || LAYOUT_FIELDS.some(field => Object.hasOwn(patch, field)) }
}

/**
 * Whether a pending clip's layout is still the default it was created with
 * for this video type — i.e. the user has not chosen a layout of their own
 * while the analysis was outstanding.
 */
export function layoutUntouched(edit: ClipEditState, videoType: VideoType): boolean {
  if (edit.layoutChosen) return false
  const defaults = initialClipEditForVideoType(videoType)
  return LAYOUT_FIELDS.every((field) => (edit[field] ?? false) === (defaults[field] ?? false))
}

/**
 * Graft the result of a reframe analysis onto the current copy of a clip.
 *
 * The analysis owns the focus track and the content classification, which
 * are always taken. It also proposes layout defaults (crop vs letterbox,
 * auto vs manual framing, the starting focus, whether auto zoom makes sense)
 * — those are applied only while the clip still has the layout it was
 * created with; a user who picked letterbox or dragged the focus slider
 * while waiting keeps their choice. Everything else — title, trim, caption
 * style, B-roll, the social caption — belongs to whoever has been editing
 * the clip and is kept from `current`. Used on both sides of the IPC
 * boundary so the renderer's local state and the saved project converge on
 * the same clip.
 */
export function mergeReframeResult(current: Clip, analysed: Clip, videoType: VideoType, retryLayout = false): Clip {
  const merged: Clip = {
    ...current,
    focusTrack: analysed.focusTrack,
    contentType: analysed.contentType,
    visualLayout: (current.visualLayout?.revision ?? 0) > 0 &&
      (current.visualLayout?.revision ?? 0) >= (analysed.visualLayout?.revision ?? 0)
      ? current.visualLayout : analysed.visualLayout,
    reframeAnalysis: analysed.reframeAnalysis ?? {
      start: analysed.suggestedStart, end: analysed.suggestedEnd, version: 0
    },
    reframeStatus: analysed.reframeStatus ?? 'done'
  }
  if (needsReframe(merged)) merged.reframeStatus = 'pending'
  const retryAutomatic = retryLayout && !current.edit.layoutChosen && !current.visualLayout?.revision
  if (!layoutUntouched(current.edit, videoType) && !needsLayoutUpgrade(current) && !retryAutomatic) return merged
  return {
    ...merged,
    edit: {
      ...current.edit,
      reframeMode: analysed.edit.reframeMode,
      framing: analysed.edit.framing,
      focusX: analysed.edit.focusX,
      autoZoom: analysed.edit.autoZoom
    }
  }
}
